name: Build and deploy pipeline for Movies API

on:
  push:
    branches:
      - main

env:
  DOTNET_VERSION: "8.0.x"
  DOTNET_NOLOGO: true
  DOTNET_CLI_TELEMETRY_OPTOUT: true

jobs:
  build-test-deploy:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Run .NET Build, Test, Publish
        run: |
          dotnet restore
          dotnet build --configuration Release --no-restore
          dotnet test --no-build --no-restore --verbosity minimal
          dotnet publish --configuration Release --no-restore

      - name: Upload app artifact
        uses: actions/upload-artifact@v4
        with:
          name: app
          path: ./src/MoviesApi/bin/Release/publish

      - name: Generate SBOM
        run: |
          curl -Lo $RUNNER_TEMP/sbom-tool https://github.com/microsoft/sbom-tool/releases/latest/download/sbom-tool-linux-x64
          chmod +x $RUNNER_TEMP/sbom-tool
          $RUNNER_TEMP/sbom-tool generate -b . -bc . -pn ${{ github.repository }} -pv 1.0.0 -ps ${{ github.repository_owner }} -nsb https://sbom.mycompany.com -V Verbose

      - name: Upload SBOM artifact
        uses: actions/upload-artifact@v4
        with:
          name: sbom
          path: _manifest/spdx_2.2
      - uses: advanced-security/spdx-dependency-submission-action@v0.1.1
        with:
          filePath: "_manifest/spdx_2.2/"

      - uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Provision Azure infrastructure using Pulumi
        uses: pulumi/actions@v5
        id: pulumi
        with:
          command: up
          stack-name: dev
          work-dir: ./infra/MoviesApi.Infra
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}

      - name: Deploy code to Azure App Service
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ steps.pulumi.outputs.AppName }}
          package: ./src/MoviesApi/bin/Release/publish

      - run: az logout