name: Build and deploy pipeline for Movies API

on:
  push:
    branches:
      - main

env:
  DOTNET_VERSION: "8.0.x"
  DOTNET_NOLOGO: true
  DOTNET_CLI_TELEMETRY_OPTOUT: true

permissions:
  id-token: write
  contents: read

jobs:
  build-test-deploy:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    services:
      azurite:
        image: mcr.microsoft.com/azure-storage/azurite
        ports:
          - 10000:10000 # Blob service
          - 10001:10001 # Queue service
          - 10002:10002 # Table service
        options: >-
          --env AZURITE_ACCOUNTS=devstoreaccount1:MDFKRjVWOVRNSDBQWEhKOUtIVDBCUjYzM0Y=

    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Run .NET Restore
        run: dotnet restore

      - name: Run .NET Build
        run: dotnet build --configuration Release --no-restore

      - name: Run .NET Test
        env:
          StorageConnectionString: DefaultEndpointsProtocol=http;AccountName=devstoreaccount1;AccountKey=MDFKRjVWOVRNSDBQWEhKOUtIVDBCUjYzM0Y=;TableEndpoint=http://127.0.0.1:10002/devstoreaccount1;
        run: dotnet test --configuration Release --no-build --no-restore --verbosity minimal

      - name: Run .NET Publish
        run: dotnet publish --configuration Release --no-restore

      - name: Upload app artifact
        uses: actions/upload-artifact@v4
        with:
          name: app
          path: ./src/MoviesApi/bin/Release/net8.0/publish

      - name: Generate SBOM
        run: |
          curl -Lo $RUNNER_TEMP/sbom-tool https://github.com/microsoft/sbom-tool/releases/latest/download/sbom-tool-linux-x64
          chmod +x $RUNNER_TEMP/sbom-tool
          $RUNNER_TEMP/sbom-tool generate -b . -bc . -pn ${{ github.repository }} -pv 1.0.0 -ps ${{ github.repository_owner }} -nsb https://sbom.mycompany.com -V Information

      - name: Upload SBOM artifact
        uses: actions/upload-artifact@v4
        with:
          name: sbom
          path: _manifest/spdx_2.2

      - uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Provision Azure infrastructure using Pulumi
        uses: pulumi/actions@v6
        id: pulumi
        with:
          command: up
          stack-name: dev
          work-dir: ./infra/MoviesApi.Infra
        env:
          ARM_USE_OIDC: true
          ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
          ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}

      - name: Deploy code to Azure App Service
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ steps.pulumi.outputs.AppName }}
          package: ./src/MoviesApi/bin/Release/net8.0/publish

      - run: az logout